### ISSUE TITLE
RabbitMQ issue when running docker-compose

### ISSUE THREAD

**Issue by ptdkm1** [Bayer-Group/COLID-Setup#1]
Dear Team,

I have been trying to try out the Docker containers that you provide, but I come across an issue that could be related to RabbitMQ. Would you perhaps be able to share some insights?

I have installed Docker Desktop on a Windows 10, and have followed the steps that you detail in the README. However, when I run docker-compose, the _rabbitmq_ container seems to fail with the following messages:

![rabbitmq](https://user-images.githubusercontent.com/88321563/127852987-9282ced6-4415-466a-aaa0-db1549ad4c55.PNG)

The COLID services appear to be launching, but with errors:

![gen](https://user-images.githubusercontent.com/88321563/127853027-221bc6cd-f34a-45f2-9a2d-05a3a2dacdd1.PNG)

When I try to "Start reindex" under _Administration > Metadata Graph Configuration_ according to Step 7 of the Installation Instructions, I get an error:

![colid](https://user-images.githubusercontent.com/88321563/127853358-fc8bc532-3b38-4c35-a25a-8b01431bf60b.gif)

Do you perhaps have some intuition on what is going on? Is there something I might have missed?

Many thanks for any help that you can give us, and keep up the good work!

**Comment by kanwalmeet** [comment]
Hi, 
Thanks for reaching out to us. Could you please confirm if you are using the .env file to set up the following variables

- MESSAGEQUEUE_COOKIE=SWQOKODSQALRPCLNMEQG
- MESSAGEQUEUE_USERNAME=guest
- MESSAGEQUEUE_PASSWORD=guest

Also would be great if you can share the message queue docker container logs to us if possible

**Comment by ptdkm1** [comment]
Thanks for the fast response! Indeed I have created an .env file in the root folder:

![env](https://user-images.githubusercontent.com/88321563/127856873-85455307-efe0-4639-aa9b-80242a5dc415.png)

Is "rabbitmq" the message queue docker container? If yes, I can see nothing else other than the error I sent in the first message. What I'm getting as logs from Docker desktop is: [rabbitmq-logs.txt](https://github.com/Bayer-Group/COLID-Setup/files/6916586/rabbitmq-logs.txt). Let me know if you're referring to something else!

**Comment by kanwalmeet** [comment]
Hello - we noticed that over the weekend this issue with deprecated variables for rabbitmq image was reported by many other projects. 
As per their new configuration docs, could you please try to remove the _RABBITMQ_ prefix in the RABBITMQ_DEFAULT_USER, PASS and VHOST variables in the docker-compose.yml file and build the images again?
![image](https://user-images.githubusercontent.com/78076833/127895790-7828dac2-db3d-455c-bc1d-a4a7db3f8bdf.png)

**Comment by ptdkm1** [comment]
It worked! (when doing the same also for the cookie) Many thanks!
