### ISSUE TITLE
KGE-Web-Service not running with docker-compose

### ISSUE THREAD

**Issue by lavdim** [Bayer-Group/COLID-Setup#2]
Hello,

I tried out to install COLID via docker-compose. During the container creation phase the KGE-Web-Service failed to be built, showing the following error:

![image](https://user-images.githubusercontent.com/1911492/140535030-b8ab7b22-e7e4-46fe-899d-30f51d3cb0c8.png)

Looking at the Dockerfile:

`
FROM node:10-alpine as build-phase
ENV PORT=8080
ENV NODE_ENV="docker"
COPY package.json package-lock.json ./

##Storing node modules on a separate layer will prevent unnecessary npm installs at each build
RUN npm install \
 && mkdir /ng-app \
 && cp -R ./node_modules ./ng-app

##3 against vulnerable packages
RUN npm audit fix

WORKDIR /ng-app

COPY . .
`

it seems that only the package.json file is copied from host to the guest. Further, the dist folder based on the typescript sources folder is not generated. 

Therefore, I modified a little bit the Dockerfile by copying the entire folder of the sources to the host and running the command for generating the dist folder:

` 
FROM node:10-alpine as build-phase
ENV PORT=8080
ENV NODE_ENV="docker"

##COPY package.json package-lock.json ./
**RUN mkdir /ng-app
COPY . ./ng-app**

##Storing node modules on a separate layer will prevent unnecessary npm installs at each build
RUN cd ./ng-app \\
&& npm install \\
**&& npm audit fix \\
 && ./node_modules/.bin/tsc**

##3 against vulnerable packages
##RUN npm audit fix

WORKDIR /ng-app

COPY . .   
`

Now, it seems that the container can be with no issue.

**Comment by kanwalmeet** [comment]
Hi Lavdim, I have made some fixes and will check and revert asap

**Comment by kanwalmeet** [comment]
made some fixes and will check and revert asap
