### ISSUE TITLE
Installing COLID on a remote server

### ISSUE THREAD

**Issue by lavdim** [Bayer-Group/COLID-Setup#3]
Hi, 

we would like to install COLID on a remote server, with its alias name, like: _server1.domain.com_. 

We have seen that each component has two different types of configuration files related to the component communication and redirection, namely: filename.local.ts and filename.docker.ts. 

When using the docker environment, some of these filename.docker.ts have http://localhost:PortNumber and in some other ones is used http:/dockerName:PortNumber. We already tried to replaced the "_http://localhost:PortNumber_" with "_http://server1.domain.com:PortNumber_", but it seems that we are missing something. As a result, the COLID interface is always on loading mode and the console is printing the following error:

`

colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:30 +0000] "GET /resource/welcome HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:30 +0000] "GET /scripts.b8e5d1190db440f00190.js HTTP/1.1" 304 0 "http://serverName.domain.com:4200/resource/welcome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:30 +0000] "GET /styles.b44528733417fc5406ce.css HTTP/1.1" 200 38931 "http://serverName.domain.com:4200/resource/welcome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:30 +0000] "GET /runtime-es2015.8a25b1b8e8d848b9dd36.js HTTP/1.1" 304 0 "http://serverName.domain.com:4200/resource/welcome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:30 +0000] "GET /polyfills-es2015.72382377d643e30d0520.js HTTP/1.1" 304 0 "http://serverName.domain.com:4200/resource/welcome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:30 +0000] "GET /main-es2015.13a4023b4a9159c609e2.js HTTP/1.1" 304 0 "http://serverName.domain.com:4200/resource/welcome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:31 +0000] "GET /assets/BAG_COLID-Visual_white_lh.svg HTTP/1.1" 200 3143 "http://serverName.domain.com:4200/resource/welcome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:31 +0000] "GET /assets/BAG_COLID-Visual_coloured_with-Claim_lh.svg HTTP/1.1" 200 10092 "http://serverName.domain.com:4200/resource/welcome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:31 +0000] "GET /assets/BAG-logo.svg HTTP/1.1" 200 2370 "http://serverName.domain.com:4200/resource/welcome" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-registration-service         | fail: COLID.Exception.ExceptionMiddleware[0]
colid-registration-service         |       A HTTP Error occurred while trying to make the SPARQL Query, see inner exception for details
colid-registration-service         | VDS.RDF.Query.RdfQueryException: A HTTP Error occurred while trying to make the SPARQL Query, see inner exception for details
colid-registration-service         |  ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
colid-registration-service         |    at System.Net.HttpWebRequest.GetResponse()
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.ExecuteQuery(Uri target, String postData, String accept)
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryInternal(String sparqlQuery, String acceptHeader)
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryWithResultSet(ISparqlResultsHandler handler, String sparqlQuery)
colid-registration-service         |    --- End of inner exception stack trace ---
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryWithResultSet(ISparqlResultsHandler handler, String sparqlQuery)
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryWithResultSet(String sparqlQuery)
colid-registration-service         |    at COLID.Graph.TripleStore.Repositories.TripleStoreRepository.QueryTripleStoreResultSet(SparqlParameterizedString queryString) in /src/libs/COLID.Graph/TripleStore/Repositories/TripleStoreRepository.cs:line 34
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.<GetLatestConfiguration>b__10_0() in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 127
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry, TimeSpan expirationTime) in /src/libs/COLID.Cache/Services/CacheService.cs:line 150
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry) in /src/libs/COLID.Cache/Services/CacheService.cs:line 135
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.GetLatestConfiguration() in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 101
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.GetGraphs(String graphType, String configIdentifier) in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 223
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.GetGraphs(IEnumerable`1 graphTypes) in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 235
colid-registration-service         |    at COLID.RegistrationService.Repositories.Implementation.TaxonomyRepository.GetTaxonomies(String type) in /src/src/COLID.RegistrationService.Repositories/Implementation/TaxonomyRepository.cs:line 84
colid-registration-service         |    at COLID.RegistrationService.Services.Implementation.TaxonomyService.<>c__DisplayClass4_0.<GetTaxonomies>b__0() in /src/src/COLID.RegistrationService.Services/Implementation/TaxonomyService.cs:line 55
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry, TimeSpan expirationTime) in /src/libs/COLID.Cache/Services/CacheService.cs:line 150
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry) in /src/libs/COLID.Cache/Services/CacheService.cs:line 135
colid-registration-service         |    at COLID.RegistrationService.Services.Implementation.TaxonomyService.GetTaxonomies(String taxonomyType) in /src/src/COLID.RegistrationService.Services/Implementation/TaxonomyService.cs:line 53
colid-registration-service         |    at lambda_method(Closure , Object , Object[] )
colid-registration-service         |    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
colid-registration-service         | --- End of stack trace from previous location where exception was thrown ---
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
colid-registration-service         | --- End of stack trace from previous location where exception was thrown ---
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
colid-registration-service         | --- End of stack trace from previous location where exception was thrown ---
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
colid-registration-service         |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
colid-registration-service         |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
colid-registration-service         |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
colid-registration-service         |    at COLID.Exception.ExceptionMiddleware.InvokeAsync(HttpContext httpContext) in /src/libs/COLID.Exception/ExceptionMiddleware.cs:line 48
colid-appdata-service              | dbug: COLID.Cache.Services.CacheService[0]
colid-appdata-service              |       Get key colid:appdataservice:docker:welcomemessageservice:editor
colid-registration-service         | fail: COLID.Exception.ExceptionMiddleware[0]
colid-registration-service         |       A HTTP Error occurred while trying to make the SPARQL Query, see inner exception for details
colid-registration-service         | VDS.RDF.Query.RdfQueryException: A HTTP Error occurred while trying to make the SPARQL Query, see inner exception for details
colid-registration-service         |  ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
colid-registration-service         |    at System.Net.HttpWebRequest.GetResponse()
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.ExecuteQuery(Uri target, String postData, String accept)
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryInternal(String sparqlQuery, String acceptHeader)
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryWithResultSet(ISparqlResultsHandler handler, String sparqlQuery)
colid-registration-service         |    --- End of inner exception stack trace ---
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryWithResultSet(ISparqlResultsHandler handler, String sparqlQuery)
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryWithResultSet(String sparqlQuery)
colid-registration-service         |    at COLID.Graph.TripleStore.Repositories.TripleStoreRepository.QueryTripleStoreResultSet(SparqlParameterizedString queryString) in /src/libs/COLID.Graph/TripleStore/Repositories/TripleStoreRepository.cs:line 34
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.<GetLatestConfiguration>b__10_0() in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 127
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry, TimeSpan expirationTime) in /src/libs/COLID.Cache/Services/CacheService.cs:line 150
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry) in /src/libs/COLID.Cache/Services/CacheService.cs:line 135
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.GetLatestConfiguration() in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 101
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.GetGraphs(String graphType, String configIdentifier) in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 223
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.GetGraphs(IEnumerable`1 graphTypes) in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 235
colid-registration-service         |    at COLID.Graph.TripleStore.Repositories.BaseRepository`1.GetNamedSubGraphs(IEnumerable`1 namedGraphs) in /src/libs/COLID.Graph/TripleStore/Repositories/BaseRepository.cs:line 370
colid-registration-service         |    at COLID.RegistrationService.Repositories.Implementation.ConsumerGroupRepository.GetConsumerGroupsByLifecycleStatus(String lifecycleStatus) in /src/src/COLID.RegistrationService.Repositories/Implementation/ConsumerGroupRepository.cs:line 45
colid-registration-service         |    at COLID.RegistrationService.Services.Implementation.ConsumerGroupService.<GetActiveEntities>b__9_0() in /src/src/COLID.RegistrationService.Services/Implementation/ConsumerGroupService.cs:line 80
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry, TimeSpan expirationTime) in /src/libs/COLID.Cache/Services/CacheService.cs:line 150
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry) in /src/libs/COLID.Cache/Services/CacheService.cs:line 135
colid-registration-service         |    at COLID.RegistrationService.Services.Implementation.ConsumerGroupService.GetActiveEntities() in /src/src/COLID.RegistrationService.Services/Implementation/ConsumerGroupService.cs:line 80
colid-registration-service         |    at lambda_method(Closure , Object , Object[] )
colid-registration-service         |    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
colid-registration-service         | --- End of stack trace from previous location where exception was thrown ---
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
colid-registration-service         | --- End of stack trace from previous location where exception was thrown ---
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
colid-registration-service         | --- End of stack trace from previous location where exception was thrown ---
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
colid-registration-service         |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
colid-registration-service         |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
colid-registration-service         |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
colid-registration-service         |    at COLID.Exception.ExceptionMiddleware.InvokeAsync(HttpContext httpContext) in /src/libs/COLID.Exception/ExceptionMiddleware.cs:line 48
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:31 +0000] "GET /assets/icons/icon-180x180.png HTTP/1.1" 200 9927 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-editor-frontend              | 10.142.179.2 - - [08/Nov/2021:11:21:31 +0000] "GET /assets/BAG_COLID-Visual_coloured_Signet_lh.svg HTTP/1.1" 200 1654 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
colid-registration-service         | fail: COLID.Exception.ExceptionMiddleware[0]
colid-registration-service         |       A HTTP Error occurred while trying to make the SPARQL Query, see inner exception for details
colid-registration-service         | VDS.RDF.Query.RdfQueryException: A HTTP Error occurred while trying to make the SPARQL Query, see inner exception for details
colid-registration-service         |  ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
colid-registration-service         |    at System.Net.HttpWebRequest.GetResponse()
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.ExecuteQuery(Uri target, String postData, String accept)
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryInternal(String sparqlQuery, String acceptHeader)
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryWithResultSet(ISparqlResultsHandler handler, String sparqlQuery)
colid-registration-service         |    --- End of inner exception stack trace ---
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryWithResultSet(ISparqlResultsHandler handler, String sparqlQuery)
colid-registration-service         |    at VDS.RDF.Query.SparqlRemoteEndpoint.QueryWithResultSet(String sparqlQuery)
colid-registration-service         |    at COLID.Graph.TripleStore.Repositories.TripleStoreRepository.QueryTripleStoreResultSet(SparqlParameterizedString queryString) in /src/libs/COLID.Graph/TripleStore/Repositories/TripleStoreRepository.cs:line 34
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.<GetLatestConfiguration>b__10_0() in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 127
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry, TimeSpan expirationTime) in /src/libs/COLID.Cache/Services/CacheService.cs:line 150
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry) in /src/libs/COLID.Cache/Services/CacheService.cs:line 135
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.GetLatestConfiguration() in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 101
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataGraphConfigurationRepository.GetGraphs(String graphType, String configIdentifier) in /src/libs/COLID.Graph/Metadata/Repositories/MetadataGraphConfigurationRepository.cs:line 223
colid-registration-service         |    at COLID.Graph.Metadata.Repositories.MetadataRepository.GetLeafEntityTypes(String firstEntityType) in /src/libs/COLID.Graph/Metadata/Repositories/MetadataRepository.cs:line 261
colid-registration-service         |    at COLID.Graph.Metadata.Services.MetadataService.<>c__DisplayClass15_0.<GetLeafEntityTypes>b__0() in /src/libs/COLID.Graph/Metadata/Services/MetadataService.cs:line 274
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry, TimeSpan expirationTime) in /src/libs/COLID.Cache/Services/CacheService.cs:line 150
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry) in /src/libs/COLID.Cache/Services/CacheService.cs:line 135
colid-registration-service         |    at COLID.Graph.Metadata.Services.MetadataService.GetLeafEntityTypes(String firstEntityType) in /src/libs/COLID.Graph/Metadata/Services/MetadataService.cs:line 273
colid-registration-service         |    at COLID.Graph.TripleStore.Services.BaseEntityService`5.GetEntities(EntitySearch search) in /src/libs/COLID.Graph/TripleStore/Services/BaseEntityService.cs:line 121
colid-registration-service         |    at COLID.RegistrationService.Services.Implementation.PidUriTemplateService.<>n__0(EntitySearch search)
colid-registration-service         |    at COLID.RegistrationService.Services.Implementation.PidUriTemplateService.<>c__DisplayClass4_0.<GetEntities>b__0() in /src/src/COLID.RegistrationService.Services/Implementation/PidUriTemplateService.cs:line 52
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry, TimeSpan expirationTime) in /src/libs/COLID.Cache/Services/CacheService.cs:line 150
colid-registration-service         |    at COLID.Cache.Services.CacheService.GetOrAdd[T](String key, Func`1 addEntry) in /src/libs/COLID.Cache/Services/CacheService.cs:line 135
colid-registration-service         |    at COLID.RegistrationService.Services.Implementation.PidUriTemplateService.GetEntities(EntitySearch search) in /src/src/COLID.RegistrationService.Services/Implementation/PidUriTemplateService.cs:line 52
colid-registration-service         |    at lambda_method(Closure , Object , Object[] )
colid-registration-service         |    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
colid-registration-service         | --- End of stack trace from previous location where exception was thrown ---
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
colid-registration-service         | --- End of stack trace from previous location where exception was thrown ---
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
colid-registration-service         | --- End of stack trace from previous location where exception was thrown ---
colid-registration-service         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
colid-registration-service         |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
colid-registration-service         |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
colid-registration-service         |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
colid-registration-service         |    at COLID.Exception.ExceptionMiddleware.InvokeAsync(HttpContext httpContext) in /src/libs/COLID.Exception/ExceptionMiddleware.cs:line 67
colid-registration-service         | Error: Unable to submit event {@logEntry}
colid-registration-service         | Error: Unable to submit event {@logEntry}
colid-registration-service         | Error: Unable to submit event {@logEntry}
colid-registration-service         | Error: Unable to submit event {@logEntry}
colid-registration-service         | Error: Unable to submit event {@logEntry}
colid-registration-service         | Error: Unable to submit event {@logEntry}

`

Best,
Lavdim

**Comment by kanwalmeet** [comment]
Hi Lavdim - I will check and get back to you

**Comment by kanwalmeet** [comment]
this was fixed after correcting the appsettings
