### ISSUE TITLE
Errors when cloning the repo

### ISSUE THREAD

**Issue by atzakas** [Bayer-Group/COLID-Setup#4]
I am following the quick start guide to run the application and it's already failing at the 1st step (cloning the repo).

After running the command `git clone --recursive https://github.com/Bayer-Group/COLID-Setup`, I get the following errors (pasting the last 5 lines):

Submodule path 'COLID-Scheduler-Service': checked out 'dc344aee510b9ad06de7496f5985cd20bed72093'
Submodule path 'COLID-Search-Service': checked out 'e3852c75474cccd3b2079f27ac6193de71a81d5c'
fatal: remote error: upload-pack: not our ref 832018bfe5c199b88772fba3c2def2290996fdbf
fatal: Fetched in submodule path 'KGE-Frontend', but it did not contain 832018bfe5c199b88772fba3c2def2290996fdbf. Direct fetching of that commit failed.
fatal:

Also, in the instructions provided (https://github.com/Bayer-Group/COLID-Setup) the following step is not clear to me:

> Create a file .env in parallel to the file docker-compose.yml and insert the following variables (example values are shown):

What does it mean "in parallel to the file docker-compose.yml"? Does it mean I should create the new file in the same directory as the .yml file and name it "docker-compose.env"?
And why do you say "example values are shown"? Does this mean that the correct values will be different for my setup? If so, where can I find them?

Many thanks

PS. I am trying this on Windows 11 using Docker version 20.10.16, build aa7e414.

**Comment by kanwalmeet** [comment]
Hello Atzakas, we are checking on this and making updates to the repo. Will update you ASAP

**Comment by atzakas** [comment]
This appears to be fixed now. I am able to clone the repo recursively.
Many thanks!

**Comment by kanwalmeet** [comment]
> 

thanks for update
