### ISSUE TITLE
Errors when running docker-compose

### ISSUE THREAD

**Issue by ProbstenHias** [Bayer-Group/COLID-Setup#5]
I am following the quick start guide and the step where you run `docker-compose up` gives me the following errors:

```bash
------
 > [colid-setup-colid-editor-frontend build-phase 8/8] RUN $(npm bin)/ng build --configuration=docker --build-optimizer=false --output-hashing=all:
#0 0.826 Node.js version v12.22.12 detected.
#0 0.826 The Angular CLI requires a minimum Node.js version of either v14.15, or v16.10.
#0 0.826 
#0 0.826 Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
#0 0.826 
------
failed to solve: executor failed running [/bin/sh -c $(npm bin)/ng build --configuration=$ANGULAR_ENVIRONMENT --build-optimizer=false --output-hashing=all]: exit code: 3
```
This error probably occurs for all submodules that have Angular CLI as a dependency and uses `node:12` in their corresponding Dockerfiles, meaning:
- [COLID-Data-Marketplace-Frontend](https://github.com/Bayer-Group/COLID-Data-Marketplace-Frontend)
- [COLID-Editor-Frontend](https://github.com/Bayer-Group/COLID-Editor-Frontend)
- [KGE-Frontend](https://github.com/Bayer-Group/KGE-Frontend)
- [COLID-ResourceRelationshipManager-Frontend](https://github.com/Bayer-Group/COLID-ResourceRelationshipManager-Frontend)

Kind Regards,
Matthias

**Comment by corinabioinformatic** [comment]
Hi @ProbstenHias , I went through all the logs and I think my problem was with the nodejs and npm installation. I am using WSL so I had installed nodejs in windows and not in WSL Ubuntu. What id did was uninstalling nodejs and npm and nvm from Windows and install it from WSL2 terminal. 
that fixed this issue you commented.
